import type { Meta, StoryObj } from "@storybook/nextjs-vite";
import { Board, Pairing, Swatch } from "./Swatch";
import { BRAND_STEPS, COSMOS_BRAND, contrast, hook } from "./tokens";
import { BrandMark } from "@/components/site/brand-mark";

/**
 * The Brand board: what the Angeronia theme layer actually changed, and what
 * it costs in contrast.
 *
 * Every value is read live from the page's own computed styles, so this board
 * cannot show a colour the site is not using.
 */
function BrandBoard() {
  return (
    <div>
      <Board title="Reference ramp — Angeronia teal against Cosmos blue">
        <p className="slds-m-bottom_medium site-measure">
          Seventeen steps, generated by <code className="slds-text-font_monospace">scripts/build-theme.mjs</code>{" "}
          from IBM Carbon Teal. Swapping these re-brands every accent,
          brand-base and focus-ring hook Cosmos derives from them. Step 50 is
          the anchor: Teal 60 is the luminance twin of Cosmos&rsquo;s{" "}
          <code className="slds-text-font_monospace">#066afe</code>.
        </p>
        <div className="sb-ramp">
          <span className="slds-text-title_caps slds-text-color_weak">Step</span>
          <span className="slds-text-title_caps slds-text-color_weak">Angeronia</span>
          <span className="slds-text-title_caps slds-text-color_weak">Cosmos</span>
          {[...BRAND_STEPS].reverse().map((step) => (
            <BrandRow key={step} step={step} />
          ))}
        </div>
      </Board>

      <Board title="Accent pairings">
        <p className="slds-m-bottom_medium site-measure">
          Colour is used by role and in pairs: text on a container uses that
          container&rsquo;s <code className="slds-text-font_monospace">on-*</code> hook.
        </p>
        <div className="sb-grid">
          {[1, 2, 3].map((n) => (
            <Pairing
              key={n}
              on={`--slds-g-color-on-accent-${n}`}
              container={`--slds-g-color-accent-container-${n}`}
            />
          ))}
        </div>
      </Board>

      <Board title="Brand teal beside the feedback families">
        <p className="slds-m-bottom_medium site-measure">
          Teal sits near SLDS&rsquo;s success green on the wheel, so they are
          shown adjacent here. If they ever read as the same signal, the answer
          is not to move the brand — it is to keep{" "}
          <code className="slds-text-font_monospace">slds-theme_success</code>{" "}
          for feedback only, which design rule 4 already requires.
        </p>
        <div className="sb-grid">
          <Swatch name="--slds-g-color-accent-container-1" label="accent-container-1 (brand)" />
          <Swatch name="--slds-g-color-success-container-1" label="success-container-1" />
          <Swatch name="--slds-g-color-warning-container-1" label="warning-container-1" />
          <Swatch name="--slds-g-color-error-container-1" label="error-container-1" />
          <Swatch name="--slds-g-color-info-container-1" label="info-container-1" />
        </div>
      </Board>

      <Board title="Lockups">
        <div className="sb-grid">
          <div className="sb-tile">
            <BrandMark />
          </div>
          <div className="sb-tile">
            <BrandMark showWord={false} size={48} />
          </div>
        </div>
      </Board>

      <Board title="Contrast matrix">
        <p className="slds-m-bottom_medium site-measure">
          The same pairings <code className="slds-text-font_monospace">npm run check:theme</code>{" "}
          asserts in CI, measured here against the live page. Text pairs are
          held to AA 4.5:1; the focus ring, which carries no text, to the 3:1
          non-text minimum.
        </p>
        <ContrastMatrix />
      </Board>
    </div>
  );
}

function BrandRow({ step }: { step: number }) {
  const value = hook(`--slds-r-color-brand-${step}`);
  return (
    <>
      <code className="slds-text-font_monospace">{step}</code>
      <span
        className="sb-ramp__bar"
        style={{ background: `var(--slds-r-color-brand-${step})` }}
        title={value}
      >
        <span className="slds-assistive-text">{`Angeronia brand ${step}: ${value}`}</span>
      </span>
      <span className="sb-ramp__bar" style={{ background: COSMOS_BRAND[step] }}>
        <span className="slds-assistive-text">{`Cosmos brand ${step}: ${COSMOS_BRAND[step]}`}</span>
      </span>
    </>
  );
}

const SURFACES = [
  "surface-1",
  "surface-2",
  "surface-3",
  "surface-container-1",
  "surface-container-2",
  "surface-container-3",
];

const PAIRS: { fg: string; bg: string; min: number }[] = [
  ...[1, 2, 3].map((n) => ({ fg: `on-accent-${n}`, bg: `accent-container-${n}`, min: 4.5 })),
  ...["accent-2", "accent-3", "on-surface-3"].flatMap((fg) =>
    SURFACES.map((bg) => ({ fg, bg, min: 4.5 })),
  ),
  ...[1, 2].map((n) => ({ fg: `on-surface-inverse-${n}`, bg: `surface-inverse-${n}`, min: 4.5 })),
  ...SURFACES.map((bg) => ({ fg: "brand-base-15", bg, min: 3 })),
];

function ContrastMatrix() {
  return (
    <div className="sb-scroll">
      <table className="sb-table">
        <caption className="slds-assistive-text">
          Contrast ratios for every colour pairing SLDS defines, in the current scheme
        </caption>
        <thead>
          <tr>
            <th scope="col">Foreground</th>
            <th scope="col">Background</th>
            <th scope="col">Ratio</th>
            <th scope="col">Minimum</th>
            <th scope="col">Result</th>
          </tr>
        </thead>
        <tbody>
          {PAIRS.map(({ fg, bg, min }) => {
            const ratio = contrast(hook(`--slds-g-color-${fg}`), hook(`--slds-g-color-${bg}`));
            return (
              <tr key={`${fg}-${bg}`}>
                <td>
                  <code className="slds-text-font_monospace">{fg}</code>
                </td>
                <td>
                  <code className="slds-text-font_monospace">{bg}</code>
                </td>
                <td>{ratio.toFixed(2)}:1</td>
                <td>{min}:1</td>
                <td>{ratio >= min ? "Pass" : "FAIL"}</td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

const meta = {
  title: "Foundations/Brand",
  component: BrandBoard,
  parameters: {
    docs: {
      description: {
        component:
          "What the Angeronia theme layer changed about Cosmos, measured " +
          "against the live page rather than a copy of the tokens.",
      },
    },
  },
} satisfies Meta<typeof BrandBoard>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Light: Story = {};

export const Dark: Story = { globals: { colorScheme: "dark" } };
