#!/usr/bin/env node
// Generates block A of `app/theme.angeronia.css`: the seventeen
// `--slds-r-color-brand-*` reference steps, re-pointed from Cosmos's electric
// blue to IBM Carbon Teal (plan §2.8.2).
//
// Swapping these seventeen values re-brands the whole system: every
// `--slds-g-color-brand-base-*`, `accent-1/2/3`, `accent-container-1/2/3`,
// `border-accent-1/2/3`, `on-accent-2/3` and focus-ring shadow in Cosmos is
// derived from them through `light-dark()`.
//
//   node scripts/build-theme.mjs           rewrite block A in place
//   node scripts/build-theme.mjs --check   exit 1 if the file is out of date
//   node scripts/build-theme.mjs --stdout  print block A only
//
// Block B (semantic overrides) and block C (typography) are hand-maintained
// and are never touched by this script.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import colors from "@carbon/colors";
import { mixOklab } from "./oklab.mjs";

const here = dirname(fileURLToPath(import.meta.url));
export const THEME_FILE = resolve(here, "../app/theme.angeronia.css");

export const BEGIN = "/* === BEGIN BLOCK A — generated by scripts/build-theme.mjs — do not edit === */";
export const END = "/* === END BLOCK A === */";

const teal = colors.teal;

// SLDS reference step → how it is sourced from the Carbon teal ramp.
// A Carbon stop where the two ramps line up; an OKLab midpoint of the two
// neighbouring stops where SLDS has a step Carbon does not; step 5 is Teal 100
// carried 55 % toward black, because SLDS's darkest step sits below Carbon's.
//
// The anchor is step 50 ↔ Teal 60 `#007d79`: the luminance twin of Cosmos's
// `#066afe` (Y 0.160 vs 0.175), which keeps every contrast pairing Cosmos
// designed around.
const RECIPE = [
  { step: 5, source: "Teal 100 → black 55%", mix: [teal[100], "#000000", 0.55] },
  { step: 10, source: "Teal 100", mix: [teal[100], teal[100], 0] },
  { step: 15, source: "mid(Teal 90, Teal 100)", mix: [teal[90], teal[100], 0.5] },
  { step: 20, source: "Teal 90", mix: [teal[90], teal[90], 0] },
  { step: 30, source: "Teal 80", mix: [teal[80], teal[80], 0] },
  { step: 35, source: "mid(Teal 70, Teal 80)", mix: [teal[70], teal[80], 0.5] },
  { step: 40, source: "Teal 70", mix: [teal[70], teal[70], 0] },
  { step: 45, source: "mid(Teal 60, Teal 70)", mix: [teal[60], teal[70], 0.5] },
  { step: 50, source: "Teal 60 — the anchor", mix: [teal[60], teal[60], 0] },
  { step: 55, source: "mid(Teal 50, Teal 60)", mix: [teal[50], teal[60], 0.5] },
  { step: 60, source: "Teal 50", mix: [teal[50], teal[50], 0] },
  { step: 65, source: "mid(Teal 40, Teal 50)", mix: [teal[40], teal[50], 0.5] },
  { step: 70, source: "Teal 40", mix: [teal[40], teal[40], 0] },
  { step: 80, source: "Teal 30", mix: [teal[30], teal[30], 0] },
  { step: 85, source: "mid(Teal 20, Teal 30)", mix: [teal[20], teal[30], 0.5] },
  { step: 90, source: "Teal 20", mix: [teal[20], teal[20], 0] },
  { step: 95, source: "Teal 10", mix: [teal[10], teal[10], 0] },
];

/** The seventeen steps as `{ step, hex, source }`, darkest first. */
export function brandRamp() {
  return RECIPE.map(({ step, source, mix }) => ({
    step,
    source,
    hex: mixOklab(mix[0], mix[1], mix[2]),
  }));
}

/** Block A, including its BEGIN/END markers, with a trailing newline. */
export function generateBlockA() {
  const ramp = brandRamp();
  const width = Math.max(...ramp.map((r) => `  --slds-r-color-brand-${r.step}: ${r.hex};`.length));
  const rows = ramp.map((r) => {
    const decl = `    --slds-r-color-brand-${r.step}: ${r.hex};`;
    return `${decl.padEnd(width + 2)} /* ${r.source} */`;
  });

  return [
    BEGIN,
    "/*",
    " * The Angeronia brand ramp: IBM Carbon Teal, mapped onto SLDS 2's",
    " * seventeen-step brand reference scale (5 darkest … 95 lightest).",
    " *",
    " * Provenance: @carbon/colors teal — Apache-2.0. Steps SLDS defines but",
    " * Carbon does not are OKLab midpoints of the neighbouring Carbon stops,",
    " * so lightness stays monotonic and Cosmos's contrast pairings survive.",
    " *",
    " * Regenerate with `npm run build:theme`. `npm run check:theme` fails the",
    " * build if this block drifts from the generator.",
    " */",
    "@layer theme {",
    "  :where(html) {",
    ...rows,
    "  }",
    "}",
    END,
    "",
  ].join("\n");
}

function main() {
  const args = new Set(process.argv.slice(2));
  const block = generateBlockA();

  if (args.has("--stdout")) {
    process.stdout.write(block);
    return;
  }

  const current = readFileSync(THEME_FILE, "utf8");
  const start = current.indexOf(BEGIN);
  const stop = current.indexOf(END);
  if (start === -1 || stop === -1) {
    console.error(`${THEME_FILE}: block A markers not found.`);
    process.exit(1);
  }
  const next = current.slice(0, start) + block + current.slice(stop + END.length + 1);

  if (args.has("--check")) {
    if (next !== current) {
      console.error(
        "theme block A is out of date — run `npm run build:theme` and commit the result.",
      );
      process.exit(1);
    }
    console.log("theme block A is up to date.");
    return;
  }

  writeFileSync(THEME_FILE, next);
  console.log(`wrote block A (${RECIPE.length} steps) to app/theme.angeronia.css`);
}

if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) main();
